### ISSUE TITLE
Support Bevy 0.11

### ISSUE THREAD

**Issue by VitalyAnkh** [tasgon/bevy_iced#17]
[Bevy 0.11 is out](https://bevyengine.org/news/bevy-0-11/)! Could bevy_iced update to bevy 0.11?

**Comment by tasgon** [comment]
There's already a PR up for that, #16. I'll review that soon, but I can't publish it to crates.io anyway until iced updates their crate to use the same wgpu as bevy.

**Comment by jsatka** [comment]
I just opened PR https://github.com/tasgon/bevy_iced/pull/17 with iced crate dependencies pointing to currently most recent master branch commit. Those versions can be updated once iced 0.10 is released but the PR version of bevy_iced can already be used in the meanwhile with bevy 0.11.
