### ISSUE TITLE
bevy_iced leaks wgpu

### ISSUE THREAD

**Issue by kulkalkul** [tasgon/bevy_iced#3]
https://github.com/tasgon/bevy_iced/blob/3216dd2cfeb04c587af79c7fa55c945a8e35a016/src/lib.rs#L51

This leaks wgpu, which causes auto completion to add it as a valid import:
![image](https://user-images.githubusercontent.com/1013994/223569196-4e700450-5003-4804-8e4d-67965b616015.png)

While it is not something serious, it would be a good QoL improvement imo.

**Comment by tasgon** [comment]
I've been thinking about this, and this seems to be an unfortunate side effect of iced_wgpu exposing wgpu. The only real way to fix it would be to remove the iced_wgpu export, but then every used of bevy_iced would have to also add iced_wgpu to their package list. I'm not sure if that's a better user experience or not.

(It also feels weird singling out the iced_wgpu crate by itself, but not doing that here would mean users would also have to add iced_native as a dependency, which doesn't feel like an improvement.)
