### ISSUE TITLE
bevy 0.10.0

### ISSUE THREAD

**Issue by kulkalkul** [tasgon/bevy_iced#4]
I love it so far, thanks for the crate! Do you plan on upgrading it to 0.10.0 anytime soon?

**Comment by tasgon** [comment]
Aiming for this weekend.

**Comment by kulkalkul** [comment]
I was messing around with a local repo to see if I can update it and found out that bevy 0.10 uses wgpu 0.15.1 while iced_wgpu is still on 0.14.2. I don't know if this is solveable without editing iced_wgpu.

**Comment by tasgon** [comment]
Just took a look at it, and yeah, looks like that will have to be updated on iced's side. That also means wgpu_glyph needs to be updated, but looks like [there's already a PR for that](https://github.com/hecrj/wgpu_glyph/pull/95). 

Sorry I couldn't take a look at it last weekend, had some stuff come up.
